### ISSUE TITLE
Firmware Decryption

### ISSUE THREAD

**Issue by Hillsie** [BRH-Media/ArcConfigViewer#1]
Thanks for this. Any chance you could describing how to decrypt the firmware? Soz, I don't speak c#.
 If you have any suggestions, that would be great: I'm interested to figure out what tool chain setup on linux is required to, decrypt/decompile, compile the firmware.

**Comment by Brhsoftco** [comment]
Hi there!

This project caters to decryption of the modem configuration files (ArcFirmwareDecrypter was meant as a test for a library I found), which was discovered by rooting the LH1000 via an undisclosed exploit. Someone over on a private Slack channel reversed the ELF httpd binary that the modem uses and got the decryption key (key is in the source code [here](https://github.com/BRH-Media/ArcConfigViewer/blob/master/ArcProcessor/ArcArchive.cs#L15)).

Decrypting the firmware is actually a lot more difficult, since it's nowhere near standardised. The gist is that a *.w.ArcSigned file contains the payload. The byte layout looks like this:

| Offset | Length | Description                                                                                                                                                    |
|-------------|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 0x000       | 512    | Signed HMAC. A public key on the modem verifies it.                                                                                                            |
| 0x200       | 32     | AES-CBC-128 intialisation vector for the header block. Only the first 16 bytes are used; the next 16 are ignored.                                              |
| 0x224       | 636    | Header block. When decrypted with the key found inside a certain firmware executable (use Ghidra), it contains data used to decrypt the main firmware payload. |
| 0x4A0       | EOF    | AES-CBC-128 main firmware payload.                                                                                                                             |

The tools needed are:
- binwalk
- Ghidra (OpenJDK required) or a similar reversing suite
- Python
- OpenSSL
- GNU standard toolchain

Most of the above are preinstalled on Linux, with the exception of a few.

The modem itself runs a modified variant of BusyBox, which is an open-source embedded suite of tools, but the specifics still aren't that well-known. You're better off trying to focus on getting OpenWRT to run - it's unofficial and people haven't been able to get VDSL working correctly.

Of course, I can't take credit for all the wonderful work people are doing. Most of the stuff being examined is past my knowledge level, and without people focusing on the efforts, the LH1000 will simply never achieve unlocked status.

**Comment by Hillsie** [comment]
Much appreciated. :1st_place_medal:

**Comment by Hillsie** [comment]
Much appreciated. :1st_place_medal:
